### ISSUE TITLE
Response Size in Log Files

### ISSUE THREAD

**Issue by mfilosa** [mfilosa/Monitor-Docs#1]
IBM is looking for response size for any downloads or uploads in babeld.log and unicorn.log

@celsmore @beetle-ibm @ddumontatibm

**Comment by mfilosa** [comment]
These do appear to be in the audit.log for pushes and pull so for some transactions this is supported.

**Comment by ddumontatibm** [comment]
Excellent.      I've just completed a node project to pull down the rotated logs from the ghe server and upload them to our scmon server.   Working on a user export function next.

**Comment by mfilosa** [comment]
I am going to close this out seems as though this is working for you.

**Comment by beetle-ibm** [comment]
Wait... We still need response size in the unicorn.log.  Also on the audit.log I am not clear on what's what.  
on pull I see these... (same record)
"uploaded_bytes":453
"uploaded_bytes_last":1439245473 
What do these mean exactly?

**Comment by mfilosa** [comment]
We have documented this requirement in a customer feedback issue internally in our customer feedback repository Issue #460.
